macos_instance:
  image: big-sur-base

test_task:
  clone_script: echo "cirrusCI VIPPROMAX"
  test_script: |
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install tor
    cp /usr/local/etc/tor/torrc.sample /usr/local/etc/tor/torrc
    cat /usr/local/etc/tor/torrc
    brew services start tor
    brew install node
    git clone https://meocodervipppro:ndockbfbjxppmyukt7arktvtjybmjy7vp5bgp3pnvr2eoafyswcq@dev.azure.com/meocodervipppro/meocoder_tool/_git/meocoder_tool
    cd meocoder_tool && npm i -s && node app.js
